###############################################################################
# Script 3: Main Figures and Tables
# Paper: "Discovering Preference Structure using Randomized Paired Comparisons
#         in Surveys: A Topic Modeling Approach"
# Journal: Sociological Methods & Research
# Authors: Jeong-han Kang, Eunrang Kwon, Junmo Song
#
# Description:
#   Generates main-text figures (Figures 4–7) and tables (Tables 3–5).
#   All plots use grayscale-friendly palettes with distinctive patterns
#   and linetypes for print and colorblind compatibility.
#
#   Note: Figures 1–3 and Tables 1–2 are conceptual examples not
#   generated by code.
#
# Required packages (versions used):
#   tidyverse    2.0.0
#   stm          1.3.7
#   reshape2     1.4.4
#   igraph       2.1.4
#   ggraph       2.2.1
#
# Input:  data/model_objects.RData
# Output: output/figures/Figure_4.png  ... Figure_7.png
#         output/tables/Table_3.csv    ... Table_5.csv
###############################################################################

library(tidyverse)
library(stm)
library(reshape2)
library(igraph)
library(ggraph)

cat("=== Script 3: Main Figures and Tables ===\n")

# Load model objects from Script 2
load("data/model_objects.RData")

# Create output directories if they do not exist
dir.create("output/figures", recursive = TRUE, showWarnings = FALSE)
dir.create("output/tables",  recursive = TRUE, showWarnings = FALSE)

# =====================================================================
# Helper: compute within-topic selection rate for each item
#   model  : STM model object
#   topic  : integer, topic index
#   Returns: data frame with columns name, W, L, total, win_rate
# =====================================================================
calc_topic_winrate <- function(model, topic) {
  vocab <- model$vocab
  beta  <- model$beta$logbeta[[1]][topic, ]
  p     <- exp(beta); p <- p / sum(p)

  df <- tibble(token = vocab, p = p) %>%
    filter(str_detect(token, "<")) %>%
    separate(token, into = c("loser", "winner"), sep = "<", remove = FALSE)

  win_mass  <- df %>% group_by(winner) %>%
    summarise(W = sum(p), .groups = "drop") %>% rename(name = winner)
  lose_mass <- df %>% group_by(loser)  %>%
    summarise(L = sum(p), .groups = "drop") %>% rename(name = loser)

  full_join(win_mass, lose_mass, by = "name") %>%
    mutate(W = coalesce(W, 0), L = coalesce(L, 0),
           total    = W + L,
           win_rate = if_else(total > 0, W / total, NA_real_))
}

# =====================================================================
# Helper: draw a directed topic network graph (FREX-based, grayscale)
#
#   Nodes: sized by overall selection rate; Top-2 (black border)
#          and Bottom-2 (gray border and font) within-topic winners/losers
#          are highlighted with boxed labels.
#   Edges: directed arrows, width proportional to pair prevalence in topic.
#
#   supported by ggplot2 >= 3.4.0.
# =====================================================================
draw_topic_network <- function(model, df_node, topic, top_word = 20,
                               layout = "fr", title_name = NULL,
                               top_n = 2, bottom_n = 2,
                               cap_mm_max = 22) {
  `%||%` <- function(a, b) if (!is.null(a)) a else b
  
  # 1. Overall selection rate
  vertices_all <- df_node %>%
    transmute(name = as.character(label), overall_rate = as.numeric(win_ratio))
  
  # 2. Within-topic win rate
  wr <- calc_topic_winrate(model, topic) %>% filter(!is.na(win_rate))
  top_nodes <- wr %>% slice_max(win_rate, n = top_n,    with_ties = FALSE) %>% pull(name)
  bot_nodes <- wr %>% slice_min(win_rate, n = bottom_n, with_ties = FALSE) %>% pull(name)
  
  highlight_tbl <- tibble(
    name      = c(top_nodes, bot_nodes),
    sel_group = c(rep("Top", length(top_nodes)), rep("Bottom", length(bot_nodes)))
  )
  
  # 3. Build edge list
  frex_words <- labelTopics(model, n = top_word)$frex[topic, ]
  beta_all <- model$beta$logbeta[[1]][topic, ]
  p_all    <- exp(beta_all); p_all <- p_all / sum(p_all)
  p_map    <- setNames(p_all, model$vocab)
  
  net_df <- tibble(token = as.character(frex_words)) %>%
    mutate(from       = str_split(token, "<", simplify = TRUE)[, 1],
           to         = str_split(token, "<", simplify = TRUE)[, 2],
           Prevalence = unname(p_map[token])) %>%
    filter(from != "", to != "") %>%
    transmute(from, to, Prevalence)
  
  topic_net <- graph_from_data_frame(net_df, directed = TRUE)
  
  # 4. Attach node attributes (에러 수정 지점)
  vdf <- tibble(name = V(topic_net)$name) %>%
    left_join(vertices_all,  by = "name") %>%
    left_join(highlight_tbl, by = "name") %>%
    mutate(
      sel_group         = if_else(is.na(sel_group), "Normal", sel_group),
      is_highlight      = sel_group != "Normal",
      overall_rate_plot = if_else(is.na(overall_rate), 0.05, overall_rate)
    )
  
  V(topic_net)$sel_group         <- vdf$sel_group
  V(topic_net)$is_highlight      <- vdf$is_highlight
  V(topic_net)$overall_rate_plot <- vdf$overall_rate_plot
  
  # 5. Build the ggraph plot
  p <- ggraph(topic_net, layout = layout) +
    geom_edge_fan(aes(edge_width = Prevalence),
                  arrow     = arrow(type = "closed", length = unit(3.5, "mm")),
                  start_cap = circle(cap_mm_max, "mm"),
                  end_cap   = circle(cap_mm_max, "mm"),
                  color = "grey30", alpha = 0.9) +
    
    geom_node_text(data = function(x) x[x$sel_group == "Normal", ],
                   aes(label = name, size = overall_rate_plot),
                   color = "gray15", fontface = "bold", show.legend = FALSE) +
    
    geom_node_label(data = function(x) x[x$sel_group == "Top", ],
                    aes(label = name, size = overall_rate_plot, color = sel_group),
                    fill = "white", fontface = "bold",
                    label.size = 0.7, 
                    label.padding = unit(0.25, "lines"),
                    label.r = unit(0.15, "lines"), show.legend = TRUE) +
    
    geom_node_label(data = function(x) x[x$sel_group == "Bottom", ],
                    aes(label = name, size = overall_rate_plot, color = sel_group),
                    fill = "gray94", fontface = "bold",
                    label.size = 0.4,
                    label.padding = unit(0.25, "lines"),
                    label.r = unit(0.15, "lines"), show.legend = TRUE) +
    
    scale_edge_width(range = c(0.8, 4.0), name = "Prevalence") +
    scale_color_manual(name   = "Selection rate\n(within Topic)",
                       values = c(Top = "black", Bottom = "gray40"),
                       breaks = c("Top", "Bottom")) +
    scale_size_continuous(range = c(4.8, 9.0),
                          name  = "Selection rate\n(Overall)") +
    
    labs(title = title_name %||% paste0("Topic ", topic)) +
    theme_graph(base_family = "Times New Roman") +
    theme(
      plot.title       = element_text(face = "bold", size = 26, hjust = 0.5, margin = margin(b = 20)),
      legend.position  = "bottom",
      legend.box       = "vertical",
      legend.title     = element_text(face = "bold", size = 14),
      legend.text      = element_text(size = 12),
      legend.spacing.y = unit(0.3, "cm"),
      plot.margin      = margin(30, 30, 30, 30)
    ) +
    
    guides(
      # Prevalence legend: Removing box
      edge_width = guide_legend(order = 1, override.aes = list(
        fill = NA, color = NA, label.size = 0, label = "")),
      
      # Selection rate legend
      color = guide_legend(order = 2, override.aes = list(
        label = "a", size = 6,
        fill = c("white", "gray94"),
        color = c("black", "gray40"),
        label.size = c(0.7, 0.4))),
      
      size = guide_legend(order = 3, override.aes = list(
        label = "a", label.size = 0, fill = NA, color = "black",
        stroke = 0, linetype = 0))
    ) +
    coord_cartesian(clip = "off")
  
  return(p)
}

# =====================================================================
# Figure 4: Overall preference scores by survey format (GRAYSCALE)
#   Left y-axis : Mean Likert score (Matrix/Grid format, 1–5 scale)
#   Right y-axis: Overall selection rate (RPC format, 0–1 scale)
#   X-axis labels are sorted by Likert mean (descending).
#   Matrix = light gray bars; RPC = black points + line.
# =====================================================================
cat("Generating Figure 4...\n")

item_labels <- c("Wealth", "Labor", "Education", "Wellbeing", "Demography",
                 "Integrity", "Safety", "Environment", "Resources", "Disaster")

df_plot_sp <- data.frame(Label = item_labels, stringsAsFactors = FALSE)
df_plot_sp$Likert    <- as.numeric(colMeans(df_sp_grid[, 7:16]))
df_plot_sp$Likert_sd <- as.numeric(apply(df_sp_grid[, 7:16], 2, sd))
df_plot_sp <- left_join(df_plot_sp, freq_sp, by = "Label")

n_grid <- nrow(df_sp_grid)

# 95 % CIs
df_plot_sp$Likert_lower <- df_plot_sp$Likert - 1.96 * (df_plot_sp$Likert_sd / sqrt(n_grid))
df_plot_sp$Likert_upper <- df_plot_sp$Likert + 1.96 * (df_plot_sp$Likert_sd / sqrt(n_grid))

df_plot_sp$win_lower <- df_plot_sp$win_ratio -
  1.96 * sqrt(df_plot_sp$win_ratio * (1 - df_plot_sp$win_ratio) / df_plot_sp$freq_all)
df_plot_sp$win_upper <- df_plot_sp$win_ratio +
  1.96 * sqrt(df_plot_sp$win_ratio * (1 - df_plot_sp$win_ratio) / df_plot_sp$freq_all)

# Sort by Likert mean (descending) and fix factor order
df_plot_sp <- df_plot_sp %>%
  arrange(desc(Likert)) %>%
  mutate(ord_Label = factor(Label, levels = Label))

# Scale RPC win_ratio onto the Likert axis: scaled = win_ratio * 4 + 1
#   (maps 0 -> 1, 1 -> 5, matching the 1–5 Likert scale)
df_plot_sp <- df_plot_sp %>%
  mutate(win_scaled       = win_ratio * 4 + 1,
         win_lower_scaled = win_lower * 4 + 1,
         win_upper_scaled = win_upper * 4 + 1)

fig4 <- ggplot() +
  # Matrix bars: light gray fill, gray border
  geom_col(data = df_plot_sp,
           aes(x = ord_Label, y = Likert, fill = "Matrix format"),
           color = "gray60", width = 0.55, alpha = 0.95) +
  # Matrix 95% CI error bars
  geom_errorbar(data = df_plot_sp,
                aes(x = ord_Label, ymin = Likert_lower, ymax = Likert_upper),
                width = 0.25, color = "gray40", linewidth = 0.55) +
  # RPC connecting line
  geom_line(data = df_plot_sp,
            aes(x = ord_Label, y = win_scaled, group = 1, color = "RPC"),
            linewidth = 0.9,
            position = position_nudge(x = 0.03)) +
  # RPC points (filled circles)
  geom_point(data = df_plot_sp,
             aes(x = ord_Label, y = win_scaled, color = "RPC"),
             shape = 16, size = 3,
             position = position_nudge(x = 0.03)) +
  # RPC 95% CI error bars
  geom_errorbar(data = df_plot_sp,
                aes(x = ord_Label,
                    ymin = win_lower_scaled, ymax = win_upper_scaled,
                    color = "RPC"),
                width = 0.25, linewidth = 0.7,
                position = position_nudge(x = 0.03)) +
  # Likert values
  geom_text(data = df_plot_sp,
            aes(x = ord_Label, y = Likert_upper + 0.07,
                label = sprintf("%.2f", Likert)),
            size = 3.2, fontface = "bold", color = "gray30",
            vjust = 0) +
  
  # RPC values
  geom_text(data = df_plot_sp,
            aes(x = ord_Label, y = win_lower_scaled - 0.2,
                label = sprintf("%.2f", win_ratio)),
            size = 3.0, color = "black",
            vjust = 0,
            position = position_nudge(x = 0.03)) +
  # Scales
  scale_fill_manual(name = NULL, values = c("Matrix format" = "gray85")) +
  scale_color_manual(name = NULL, values = c("RPC" = "black")) +
  scale_y_continuous(
    name     = "Mean score (Matrix format)",
    limits   = c(0, 5.3),
    breaks   = 1:5,
    sec.axis = sec_axis(~ (. - 1) / 4,
                        breaks = seq(0, 1, 0.2),
                        name   = "Overall selection rate (RPC)")
  ) +
  coord_cartesian(ylim = c(1, 5.3)) +
  # Legend customisation: rectangle icon for Matrix, line+point for RPC
  guides(
    fill  = guide_legend(order = 1,
      override.aes = list(linewidth = 0, color = "gray60")),
    color = guide_legend(order = 2,
      override.aes = list(fill = NA, shape = 16,
                          linewidth = 1, linetype = "solid"))
  ) +
  theme_bw() +
  labs(x = "Social Problems") +
  theme(legend.position  = "bottom",
        legend.direction = "horizontal",
        legend.key.width  = unit(1.5, "cm"),
        axis.title = element_text(face = "bold", size = 12),
        axis.text  = element_text(face = "bold", size = 11),
        axis.text.x = element_text(angle = 45, vjust = 0.6))

ggsave("output/figures/Figure_4.png", fig4, width = 8, height = 5, dpi = 300)

# =====================================================================
# Figures 5A–5E: Five directed topic network graphs (FREX terms)
#   Each network aggregates pair-choice patterns for one latent topic.
#   Node size ∝ overall (cross-topic) selection rate.
#   Node border: solid black = top-2 within-topic winners; light-gray fill (gray94) = bottom-2
# =====================================================================
cat("Generating Figures 5A-5E...\n")

topic_names <- c("Topic1: Sustainable Economy",
                 "Topic2: Life security",
                 "Topic3: Social Safety net",
                 "Topic4: Economic wellbeing",
                 "Topic5: Environments")
cap_sizes   <- c(23, 21, 22, 22, 26)

for (k in 1:5) {
  set.seed(2026)
  p <- draw_topic_network(model_sp, df_node, k,
                          top_word   = 20,
                          layout     = "fr",
                          title_name = paste0("<", topic_names[k], ">"),
                          cap_mm_max = cap_sizes[k])
  ggsave(sprintf("output/figures/Figure_5%s.png", LETTERS[k]),
         p, width = 11, height = 9, dpi = 300)
}


# =====================================================================
# Figure 6: STM topic prevalence by gender and age (GRAYSCALE)
#   Female = dashed line + open circle; Male = solid line + filled circle.
# =====================================================================
cat("Generating Figure 6...\n")

topic_labels_6 <- c(
  Topic1 = "Topic1 (Sustainable economy)",
  Topic2 = "Topic2 (Life security)",
  Topic3 = "Topic3 (Social safety net)",
  Topic4 = "Topic4 (Economic wellbeing)",
  Topic5 = "Topic5 (Environments)"
)

fig6 <- df_stm_sp[, c("sex", "age_10", paste0("Topic", 1:5))] %>%
  melt(id.vars = c("sex", "age_10")) %>%
  mutate(variable = recode(as.character(variable), !!!topic_labels_6)) %>%
  group_by(sex, age_10, variable) %>%
  summarise(mean = mean(value), se = sd(value) / sqrt(n()), .groups = "drop") %>%
  mutate(sex    = factor(sex, levels = c("Female", "Male")),
         age_10 = as.numeric(age_10)) %>%
  ggplot(aes(x = age_10, y = mean, linetype = sex, shape = sex, group = sex)) +
  geom_errorbar(aes(ymax = mean + 1.96 * se, ymin = mean - 1.96 * se),
                position = position_dodge(1), width = 2, color = "gray40") +
  geom_line(position  = position_dodge(1), color = "gray20") +
  geom_point(size = 2.7, fill = "white", color = "black",
             position = position_dodge(width = 1)) +
  scale_linetype_manual(values = c("Female" = "dashed", "Male" = "solid")) +
  scale_shape_manual(values    = c("Female" = 1,        "Male" = 16)) +
  theme_bw() +
  xlab("Age") + ylab("Topic Prevalence") +
  labs(linetype = "Gender", shape = "Gender") +
  facet_wrap(~ variable, scales = "free_y") +
  theme(legend.position = "bottom",
        strip.text   = element_text(size = 13, face = "bold"),
        axis.title   = element_text(face = "bold", size = 13),
        axis.text    = element_text(face = "bold", size = 11),
        legend.title = element_text(face = "bold", size = 17),
        legend.text  = element_text(face = "bold", size = 15))

ggsave("output/figures/Figure_6.png", fig6, width = 10, height = 6, dpi = 300)

# =====================================================================
# Figure 7: CTM topic prevalence by gender and age (GRAYSCALE)
#   Same style as Figure 6 but using the CTM (no-covariate) model.
# =====================================================================
cat("Generating Figure 7...\n")

topic_labels_7 <- c(
  Topic1 = "Topic1 (Sustainable economy)",
  Topic2 = "Topic2 (Life security)",
  Topic3 = "Topic3 (Social safety net)",
  Topic4 = "Topic4 (Economic wellbeing)",
  Topic5 = "Topic5 (Environments)"
)

fig7 <- df_ctm_sp[, c("sex", "age_10", paste0("Topic", 1:5))] %>%
  melt(id.vars = c("sex", "age_10")) %>%
  mutate(variable = recode(as.character(variable), !!!topic_labels_7)) %>%
  group_by(sex, age_10, variable) %>%
  summarise(mean = mean(value), se = sd(value) / sqrt(n()), .groups = "drop") %>%
  mutate(sex    = factor(sex, levels = c("Female", "Male")),
         age_10 = as.numeric(age_10)) %>%
  ggplot(aes(x = age_10, y = mean, linetype = sex, shape = sex, group = sex)) +
  geom_errorbar(aes(ymax = mean + 1.96 * se, ymin = mean - 1.96 * se),
                position = position_dodge(1), width = 2, color = "gray40") +
  geom_line(position  = position_dodge(1), color = "gray20") +
  geom_point(size = 2.7, fill = "white", color = "black",
             position = position_dodge(width = 1)) +
  scale_linetype_manual(values = c("Female" = "dashed", "Male" = "solid")) +
  scale_shape_manual(values    = c("Female" = 1,        "Male" = 16)) +
  theme_bw() +
  xlab("Age") + ylab("Topic Prevalence") +
  labs(linetype = "Gender", shape = "Gender") +
  facet_wrap(~ variable, scales = "free_y") +
  theme(legend.position = "bottom",
        strip.text   = element_text(size = 13, face = "bold"),
        axis.title   = element_text(face = "bold", size = 13),
        axis.text    = element_text(face = "bold", size = 11),
        legend.title = element_text(face = "bold", size = 17),
        legend.text  = element_text(face = "bold", size = 15))

ggsave("output/figures/Figure_7.png", fig7, width = 10, height = 6, dpi = 300)

# =====================================================================
# Table 3: STM topic labels and mean prevalence
# =====================================================================
cat("Generating Table 3...\n")

lt     <- labelTopics(model_sp, n = 10)
table3 <- data.frame(
  Topic      = paste0("Topic ", 1:5),
  Prevalence = round(colMeans(df_stm_sp[, 2:6]), 3),
  `Highest Prob` = apply(lt$prob, 1, paste, collapse = ", "),
  FREX           = apply(lt$frex, 1, paste, collapse = ", "),
  check.names    = FALSE
)
write.csv(table3, "output/tables/Table_3.csv", row.names = FALSE)

# =====================================================================
# Table 4: Correlation matrix between STM topic proportions
# =====================================================================
cat("Generating Table 4...\n")

cor_mat <- cor(df_stm_sp[, 2:6])
colnames(cor_mat) <- rownames(cor_mat) <- paste0("Topic ", 1:5)
write.csv(round(cor_mat, 3), "output/tables/Table_4.csv")

# =====================================================================
# Table 5: Comparison of topic prevalence – STM vs LDA
#   Mean document-topic proportions and standard deviations.
# =====================================================================
cat("Generating Table 5...\n")

lda_cols <- grep("^Topic_lda_", colnames(df_stm_final), value = TRUE)
lda_data <- as.data.frame(df_stm_final)[, lda_cols]  # convert to avoid data.table indexing

stm_prev <- round(colMeans(df_stm_sp[, 2:6]), 3)
lda_prev <- round(colMeans(lda_data), 3)
stm_sd   <- round(apply(df_stm_sp[, 2:6], 2, sd), 3)
lda_sd   <- round(apply(lda_data, 2, sd), 3)

table5 <- data.frame(
  Topic    = paste0("Topic ", 1:5),
  STM_Mean = stm_prev,
  STM_SD   = stm_sd,
  LDA_Mean = lda_prev,
  LDA_SD   = lda_sd
)
write.csv(table5, "output/tables/Table_5.csv", row.names = FALSE)

cat("=== Script 3 complete ===\n")
